"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type Language = "vi" | "en" | "ja"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  vi: {
    // Header
    "nav.home": "Trang chủ",
    "nav.practice": "Luyện đề",
    "nav.activate": "Kích hoạt tài khoản",
    "nav.profile": "Hồ sơ",
    "nav.login": "Đăng nhập",

    // Home page
    "home.hero.title": "Chinh phục JLPT cùng",
    "home.hero.subtitle": "JLPT Practice",
    "home.hero.description":
      "Nền tảng luyện thi năng lực tiếng Nhật hiện đại nhất Việt Nam. Hơn 10,000 học viên đã đạt chứng chỉ JLPT với chúng tôi.",
    "home.hero.start": "Bắt đầu luyện thi",
    "home.hero.demo": "Xem demo",
    "home.benefits.title": "Tại sao chọn JLPT Practice?",
    "home.benefits.subtitle": "Chúng tôi mang đến trải nghiệm học tập tốt nhất với công nghệ hiện đại",
    "home.benefits.official_tests": "Đề thi chính thức",
    "home.benefits.official_tests_desc": "Hơn 1000+ đề thi JLPT từ N5 đến N1 được cập nhật liên tục",
    "home.benefits.progress_tracking": "Theo dõi tiến độ",
    "home.benefits.progress_tracking_desc": "Thống kê chi tiết kết quả học tập và tiến độ cá nhân",
    "home.benefits.smart_practice": "Luyện tập thông minh",
    "home.benefits.smart_practice_desc": "AI phân tích điểm yếu và đề xuất bài tập phù hợp",
    "home.benefits.community": "Cộng đồng học tập",
    "home.benefits.community_desc": "Kết nối với hàng nghìn học viên khác trên toàn quốc",
    "home.pricing.title": "Chọn gói phù hợp với bạn",
    "home.pricing.subtitle": "Từ miễn phí đến cao cấp, chúng tôi có gói phù hợp cho mọi nhu cầu học tập",
    "home.pricing.free": "Miễn phí",
    "home.pricing.free_desc": "Phù hợp cho người mới bắt đầu",
    "home.pricing.monthly": "1 tháng",
    "home.pricing.monthly_desc": "Luyện tập chuyên sâu trong thời gian ngắn",
    "home.pricing.yearly": "1 năm",
    "home.pricing.yearly_desc": "Tiết kiệm 33% - Lựa chọn tốt nhất",
    "home.pricing.popular": "Phổ biến nhất",
    "home.pricing.start_free": "Bắt đầu miễn phí",
    "home.pricing.choose_plan": "Chọn gói này",
    "home.pricing.save_33": "Tiết kiệm 33%",
    "home.cta.title": "Sẵn sàng chinh phục JLPT?",
    "home.cta.subtitle": "Hãy bắt đầu hành trình học tập của bạn ngay hôm nay. Miễn phí 100%!",
    "home.cta.register": "Đăng ký ngay",

    // Practice page
    "practice.title": "Luyện đề JLPT",
    "practice.description": "Hơn 1000+ đề thi JLPT chính thức từ N5 đến N1. Luyện tập ngay để nâng cao kỹ năng!",
    "practice.search.title": "Tìm kiếm đề thi",
    "practice.search.level": "Cấp độ",
    "practice.search.year": "Năm",
    "practice.search.difficulty": "Độ khó",
    "practice.search.keyword": "Từ khóa",
    "practice.search.placeholder": "Tìm kiếm theo tên đề...",
    "practice.difficulty.easy": "Dễ",
    "practice.difficulty.medium": "Trung bình",
    "practice.difficulty.hard": "Khó",
    "practice.difficulty.very_hard": "Rất khó",
    "practice.all_levels": "Tất cả cấp độ",
    "practice.all_years": "Tất cả năm",
    "practice.all_difficulties": "Tất cả độ khó",
    "practice.view_detail": "Xem chi tiết",
    "practice.no_results": "Không tìm thấy đề thi",
    "practice.no_results_desc": "Hãy thử thay đổi bộ lọc tìm kiếm của bạn",

    // Activate page
    "activate.title": "Kích hoạt tài khoản",
    "activate.description": "Nâng cấp tài khoản để truy cập đầy đủ tính năng và tăng tốc quá trình học tập",
    "activate.current_account": "Tài khoản hiện tại",
    "activate.status": "Trạng thái",
    "activate.active": "Đang hoạt động",
    "activate.plan_free": "Miễn phí",
    "activate.plan_monthly": "1 tháng",
    "activate.plan_yearly": "1 năm",
    "activate.plan_free_desc": "Phù hợp cho người mới bắt đầu",
    "activate.plan_monthly_desc": "Luyện tập chuyên sâu trong thời gian ngắn",
    "activate.plan_yearly_desc": "Tiết kiệm 33% - Lựa chọn tốt nhất",
    "activate.features_included": "Tính năng bao gồm:",
    "activate.limitations": "Giới hạn:",
    "activate.current_plan": "Đang sử dụng",
    "activate.upgrade_now": "Nâng cấp ngay",
    "activate.processing": "Đang xử lý...",

    // Profile page
    "profile.title": "Hồ sơ cá nhân",
    "profile.description": "Quản lý thông tin tài khoản và theo dõi tiến độ học tập",
    "profile.personal_info": "Thông tin cá nhân",
    "profile.history": "Lịch sử luyện đề",
    "profile.stats": "Thống kê",
    "profile.edit": "Chỉnh sửa",
    "profile.save": "Lưu",
    "profile.cancel": "Hủy",
    "profile.name": "Họ và tên",
    "profile.email": "Email",
    "profile.join_date": "Ngày tham gia",
    "profile.current_plan": "Gói hiện tại",
    "profile.quick_stats": "Thống kê nhanh",
    "profile.exams_taken": "Đề đã làm",
    "profile.average_score": "Điểm trung bình",
    "profile.best_score": "Điểm cao nhất",
    "profile.study_time": "Thời gian học",
    "profile.exam_history": "Lịch sử luyện đề",
    "profile.exam_history_desc": "Danh sách các đề thi bạn đã hoàn thành",
    "profile.passed": "Đậu",
    "profile.failed": "Trượt",
    "profile.correct": "đúng",
    "profile.progress_chart": "Tiến độ học tập theo thời gian",
    "profile.progress_chart_desc": "Biểu đồ thể hiện sự cải thiện điểm số qua các lần thi",

    // Exam detail page
    "exam.start_exam": "Bắt đầu làm bài",
    "exam.preparing": "Đang chuẩn bị...",
    "exam.exam_info": "Thông tin đề thi",
    "exam.time": "Thời gian",
    "exam.questions": "Câu hỏi",
    "exam.participants": "Người làm",
    "exam.difficulty": "Độ khó",
    "exam.structure": "Cấu trúc đề thi",
    "exam.structure_desc": "Đề thi được chia thành 3 phần chính với thời gian làm bài riêng biệt",
    "exam.statistics": "Thống kê",
    "exam.average_score": "Điểm trung bình",
    "exam.pass_rate": "Tỷ lệ đậu",
    "exam.completion_rate": "Tỷ lệ hoàn thành",
    "exam.tips": "Lời khuyên",
    "exam.tip1": "• Đọc kỹ đề bài trước khi trả lời",
    "exam.tip2": "• Quản lý thời gian hợp lý cho từng phần",
    "exam.tip3": "• Làm những câu dễ trước",
    "exam.tip4": "• Kiểm tra lại đáp án trước khi nộp",

    // Exam taking page
    "exam_taking.question_list": "Danh sách câu hỏi",
    "exam_taking.current_question": "Câu hiện tại",
    "exam_taking.answered": "Đã trả lời",
    "exam_taking.unanswered": "Chưa trả lời",
    "exam_taking.time_warning": "Sắp hết giờ!",
    "exam_taking.time_left": "Chỉ còn",
    "exam_taking.previous": "Câu trước",
    "exam_taking.next": "Câu tiếp theo",
    "exam_taking.submit": "Nộp bài",
    "exam_taking.submitting": "Đang nộp bài...",
    "exam_taking.submit_anytime": "Bạn có thể nộp bài bất kỳ lúc nào",
    "exam_taking.completed": "hoàn thành",

    // Results page
    "results.congratulations": "Chúc mừng! Bạn đã đậu!",
    "results.not_passed": "Chưa đạt yêu cầu",
    "results.score": "Điểm số",
    "results.correct_answers": "Câu đúng",
    "results.answered": "Câu đã làm",
    "results.accuracy": "Tỷ lệ đúng",
    "results.section_performance": "Kết quả theo từng phần",
    "results.section_performance_desc": "Phân tích chi tiết điểm số theo từng kỹ năng",
    "results.detailed_results": "Chi tiết từng câu hỏi",
    "results.detailed_results_desc": "Xem lại đáp án và giải thích chi tiết",
    "results.show_details": "Xem chi tiết",
    "results.hide_details": "Ẩn chi tiết",
    "results.correct": "Đúng",
    "results.incorrect": "Sai",
    "results.no_answer": "Không trả lời",
    "results.explanation": "Giải thích:",
    "results.next_actions": "Hành động tiếp theo",
    "results.retake": "Làm lại đề này",
    "results.choose_other": "Chọn đề khác",
    "results.home": "Về trang chủ",
    "results.summary": "Tóm tắt kết quả",
    "results.total_questions": "Tổng số câu:",
    "results.questions_answered": "Câu đã làm:",
    "results.correct_count": "Câu đúng:",
    "results.incorrect_count": "Câu sai:",
    "results.passing_score": "Điểm cần đạt:",
    "results.advice": "Lời khuyên:",
    "results.advice_text": "Hãy ôn tập thêm các phần còn yếu và thử lại!",

    // Common
    "common.loading": "Đang tải...",
    "common.minutes": "phút",
    "common.questions": "câu",
    "common.participants": "người đã làm",
    "common.question": "Câu",
    "common.of": "của",
    "common.percent": "%",
  },
  en: {
    // Header
    "nav.home": "Home",
    "nav.practice": "Practice",
    "nav.activate": "Activate Account",
    "nav.profile": "Profile",
    "nav.login": "Login",

    // Home page
    "home.hero.title": "Conquer JLPT with",
    "home.hero.subtitle": "JLPT Practice",
    "home.hero.description":
      "Vietnam's most modern Japanese proficiency test preparation platform. Over 10,000 students have achieved JLPT certification with us.",
    "home.hero.start": "Start practicing",
    "home.hero.demo": "View demo",
    "home.benefits.title": "Why choose JLPT Practice?",
    "home.benefits.subtitle": "We provide the best learning experience with modern technology",
    "home.benefits.official_tests": "Official Tests",
    "home.benefits.official_tests_desc": "Over 1000+ JLPT tests from N5 to N1 updated continuously",
    "home.benefits.progress_tracking": "Progress Tracking",
    "home.benefits.progress_tracking_desc": "Detailed statistics of learning results and personal progress",
    "home.benefits.smart_practice": "Smart Practice",
    "home.benefits.smart_practice_desc": "AI analyzes weaknesses and suggests suitable exercises",
    "home.benefits.community": "Learning Community",
    "home.benefits.community_desc": "Connect with thousands of other learners nationwide",
    "home.pricing.title": "Choose the right plan for you",
    "home.pricing.subtitle": "From free to premium, we have plans suitable for all learning needs",
    "home.pricing.free": "Free",
    "home.pricing.free_desc": "Perfect for beginners",
    "home.pricing.monthly": "1 Month",
    "home.pricing.monthly_desc": "Intensive practice in a short time",
    "home.pricing.yearly": "1 Year",
    "home.pricing.yearly_desc": "Save 33% - Best choice",
    "home.pricing.popular": "Most Popular",
    "home.pricing.start_free": "Start for free",
    "home.pricing.choose_plan": "Choose this plan",
    "home.pricing.save_33": "Save 33%",
    "home.cta.title": "Ready to conquer JLPT?",
    "home.cta.subtitle": "Start your learning journey today. 100% free!",
    "home.cta.register": "Register now",

    // Practice page
    "practice.title": "JLPT Practice Tests",
    "practice.description": "Over 1000+ official JLPT tests from N5 to N1. Practice now to improve your skills!",
    "practice.search.title": "Search Tests",
    "practice.search.level": "Level",
    "practice.search.year": "Year",
    "practice.search.difficulty": "Difficulty",
    "practice.search.keyword": "Keyword",
    "practice.search.placeholder": "Search by test name...",
    "practice.difficulty.easy": "Easy",
    "practice.difficulty.medium": "Medium",
    "practice.difficulty.hard": "Hard",
    "practice.difficulty.very_hard": "Very Hard",
    "practice.all_levels": "All levels",
    "practice.all_years": "All years",
    "practice.all_difficulties": "All difficulties",
    "practice.view_detail": "View details",
    "practice.no_results": "No tests found",
    "practice.no_results_desc": "Try changing your search filters",

    // Activate page
    "activate.title": "Activate Account",
    "activate.description": "Upgrade your account to access full features and accelerate your learning process",
    "activate.current_account": "Current Account",
    "activate.status": "Status",
    "activate.active": "Active",
    "activate.plan_free": "Free",
    "activate.plan_monthly": "1 Month",
    "activate.plan_yearly": "1 Year",
    "activate.plan_free_desc": "Perfect for beginners",
    "activate.plan_monthly_desc": "Intensive practice in a short time",
    "activate.plan_yearly_desc": "Save 33% - Best choice",
    "activate.features_included": "Features included:",
    "activate.limitations": "Limitations:",
    "activate.current_plan": "Currently using",
    "activate.upgrade_now": "Upgrade now",
    "activate.processing": "Processing...",

    // Profile page
    "profile.title": "Personal Profile",
    "profile.description": "Manage account information and track learning progress",
    "profile.personal_info": "Personal Information",
    "profile.history": "Practice History",
    "profile.stats": "Statistics",
    "profile.edit": "Edit",
    "profile.save": "Save",
    "profile.cancel": "Cancel",
    "profile.name": "Full Name",
    "profile.email": "Email",
    "profile.join_date": "Join Date",
    "profile.current_plan": "Current Plan",
    "profile.quick_stats": "Quick Stats",
    "profile.exams_taken": "Exams Taken",
    "profile.average_score": "Average Score",
    "profile.best_score": "Best Score",
    "profile.study_time": "Study Time",
    "profile.exam_history": "Exam History",
    "profile.exam_history_desc": "List of tests you have completed",
    "profile.passed": "Passed",
    "profile.failed": "Failed",
    "profile.correct": "correct",
    "profile.progress_chart": "Learning Progress Over Time",
    "profile.progress_chart_desc": "Chart showing score improvement over test attempts",

    // Exam detail page
    "exam.start_exam": "Start Exam",
    "exam.preparing": "Preparing...",
    "exam.exam_info": "Exam Information",
    "exam.time": "Time",
    "exam.questions": "Questions",
    "exam.participants": "Participants",
    "exam.difficulty": "Difficulty",
    "exam.structure": "Exam Structure",
    "exam.structure_desc": "The exam is divided into 3 main sections with separate time limits",
    "exam.statistics": "Statistics",
    "exam.average_score": "Average Score",
    "exam.pass_rate": "Pass Rate",
    "exam.completion_rate": "Completion Rate",
    "exam.tips": "Tips",
    "exam.tip1": "• Read questions carefully before answering",
    "exam.tip2": "• Manage time appropriately for each section",
    "exam.tip3": "• Do easy questions first",
    "exam.tip4": "• Review answers before submitting",

    // Exam taking page
    "exam_taking.question_list": "Question List",
    "exam_taking.current_question": "Current Question",
    "exam_taking.answered": "Answered",
    "exam_taking.unanswered": "Unanswered",
    "exam_taking.time_warning": "Time running out!",
    "exam_taking.time_left": "Only",
    "exam_taking.previous": "Previous",
    "exam_taking.next": "Next",
    "exam_taking.submit": "Submit",
    "exam_taking.submitting": "Submitting...",
    "exam_taking.submit_anytime": "You can submit anytime",
    "exam_taking.completed": "completed",

    // Results page
    "results.congratulations": "Congratulations! You passed!",
    "results.not_passed": "Not passed",
    "results.score": "Score",
    "results.correct_answers": "Correct",
    "results.answered": "Answered",
    "results.accuracy": "Accuracy",
    "results.section_performance": "Section Performance",
    "results.section_performance_desc": "Detailed score analysis by skill",
    "results.detailed_results": "Detailed Question Review",
    "results.detailed_results_desc": "Review answers and detailed explanations",
    "results.show_details": "Show details",
    "results.hide_details": "Hide details",
    "results.correct": "Correct",
    "results.incorrect": "Incorrect",
    "results.no_answer": "No answer",
    "results.explanation": "Explanation:",
    "results.next_actions": "Next Actions",
    "results.retake": "Retake this test",
    "results.choose_other": "Choose another test",
    "results.home": "Go home",
    "results.summary": "Result Summary",
    "results.total_questions": "Total questions:",
    "results.questions_answered": "Questions answered:",
    "results.correct_count": "Correct:",
    "results.incorrect_count": "Incorrect:",
    "results.passing_score": "Passing score:",
    "results.advice": "Advice:",
    "results.advice_text": "Review weak areas and try again!",

    // Common
    "common.loading": "Loading...",
    "common.minutes": "minutes",
    "common.questions": "questions",
    "common.participants": "people took this",
    "common.question": "Question",
    "common.of": "of",
    "common.percent": "%",
  },
  ja: {
    // Header
    "nav.home": "ホーム",
    "nav.practice": "練習問題",
    "nav.activate": "アカウント有効化",
    "nav.profile": "プロフィール",
    "nav.login": "ログイン",

    // Home page
    "home.hero.title": "JLPTを征服しよう",
    "home.hero.subtitle": "JLPT Practice",
    "home.hero.description":
      "ベトナムで最も現代的な日本語能力試験対策プラットフォーム。10,000人以上の学習者が私たちと一緒にJLPT認定を取得しました。",
    "home.hero.start": "練習を始める",
    "home.hero.demo": "デモを見る",
    "home.benefits.title": "なぜJLPT Practiceを選ぶのか？",
    "home.benefits.subtitle": "最新技術で最高の学習体験を提供します",
    "home.benefits.official_tests": "公式試験",
    "home.benefits.official_tests_desc": "N5からN1まで1000以上のJLPT試験を継続的に更新",
    "home.benefits.progress_tracking": "進捗追跡",
    "home.benefits.progress_tracking_desc": "学習結果と個人の進捗の詳細統計",
    "home.benefits.smart_practice": "スマート練習",
    "home.benefits.smart_practice_desc": "AIが弱点を分析し、適切な練習問題を提案",
    "home.benefits.community": "学習コミュニティ",
    "home.benefits.community_desc": "全国の何千人もの他の学習者とつながる",
    "home.pricing.title": "あなたに合ったプランを選択",
    "home.pricing.subtitle": "無料からプレミアムまで、すべての学習ニーズに適したプランがあります",
    "home.pricing.free": "無料",
    "home.pricing.free_desc": "初心者に最適",
    "home.pricing.monthly": "1ヶ月",
    "home.pricing.monthly_desc": "短期間での集中練習",
    "home.pricing.yearly": "1年",
    "home.pricing.yearly_desc": "33%節約 - 最良の選択",
    "home.pricing.popular": "最も人気",
    "home.pricing.start_free": "無料で始める",
    "home.pricing.choose_plan": "このプランを選択",
    "home.pricing.save_33": "33%節約",
    "home.cta.title": "JLPTを征服する準備はできましたか？",
    "home.cta.subtitle": "今日から学習の旅を始めましょう。100%無料！",
    "home.cta.register": "今すぐ登録",

    // Practice page
    "practice.title": "JLPT練習問題",
    "practice.description": "N5からN1まで1000以上の公式JLPT試験。今すぐ練習してスキルを向上させましょう！",
    "practice.search.title": "試験検索",
    "practice.search.level": "レベル",
    "practice.search.year": "年",
    "practice.search.difficulty": "難易度",
    "practice.search.keyword": "キーワード",
    "practice.search.placeholder": "試験名で検索...",
    "practice.difficulty.easy": "簡単",
    "practice.difficulty.medium": "普通",
    "practice.difficulty.hard": "難しい",
    "practice.difficulty.very_hard": "とても難しい",
    "practice.all_levels": "すべてのレベル",
    "practice.all_years": "すべての年",
    "practice.all_difficulties": "すべての難易度",
    "practice.view_detail": "詳細を見る",
    "practice.no_results": "試験が見つかりません",
    "practice.no_results_desc": "検索フィルターを変更してみてください",

    // Activate page
    "activate.title": "アカウント有効化",
    "activate.description": "アカウントをアップグレードして全機能にアクセスし、学習プロセスを加速させましょう",
    "activate.current_account": "現在のアカウント",
    "activate.status": "ステータス",
    "activate.active": "アクティブ",
    "activate.plan_free": "無料",
    "activate.plan_monthly": "1ヶ月",
    "activate.plan_yearly": "1年",
    "activate.plan_free_desc": "初心者に最適",
    "activate.plan_monthly_desc": "短期間での集中練習",
    "activate.plan_yearly_desc": "33%節約 - 最良の選択",
    "activate.features_included": "含まれる機能：",
    "activate.limitations": "制限：",
    "activate.current_plan": "現在使用中",
    "activate.upgrade_now": "今すぐアップグレード",
    "activate.processing": "処理中...",

    // Profile page
    "profile.title": "個人プロフィール",
    "profile.description": "アカウント情報を管理し、学習進捗を追跡",
    "profile.personal_info": "個人情報",
    "profile.history": "練習履歴",
    "profile.stats": "統計",
    "profile.edit": "編集",
    "profile.save": "保存",
    "profile.cancel": "キャンセル",
    "profile.name": "氏名",
    "profile.email": "メール",
    "profile.join_date": "参加日",
    "profile.current_plan": "現在のプラン",
    "profile.quick_stats": "クイック統計",
    "profile.exams_taken": "受験回数",
    "profile.average_score": "平均スコア",
    "profile.best_score": "最高スコア",
    "profile.study_time": "学習時間",
    "profile.exam_history": "試験履歴",
    "profile.exam_history_desc": "完了した試験のリスト",
    "profile.passed": "合格",
    "profile.failed": "不合格",
    "profile.correct": "正解",
    "profile.progress_chart": "時間経過による学習進捗",
    "profile.progress_chart_desc": "試験回数によるスコア改善を示すチャート",

    // Exam detail page
    "exam.start_exam": "試験開始",
    "exam.preparing": "準備中...",
    "exam.exam_info": "試験情報",
    "exam.time": "時間",
    "exam.questions": "問題数",
    "exam.participants": "受験者",
    "exam.difficulty": "難易度",
    "exam.structure": "試験構成",
    "exam.structure_desc": "試験は3つの主要セクションに分かれ、それぞれ時間制限があります",
    "exam.statistics": "統計",
    "exam.average_score": "平均スコア",
    "exam.pass_rate": "合格率",
    "exam.completion_rate": "完了率",
    "exam.tips": "アドバイス",
    "exam.tip1": "• 回答前に問題をよく読む",
    "exam.tip2": "• 各セクションの時間を適切に管理する",
    "exam.tip3": "• 簡単な問題から先に解く",
    "exam.tip4": "• 提出前に答えを確認する",

    // Exam taking page
    "exam_taking.question_list": "問題リスト",
    "exam_taking.current_question": "現在の問題",
    "exam_taking.answered": "回答済み",
    "exam_taking.unanswered": "未回答",
    "exam_taking.time_warning": "時間切れ間近！",
    "exam_taking.time_left": "残り",
    "exam_taking.previous": "前の問題",
    "exam_taking.next": "次の問題",
    "exam_taking.submit": "提出",
    "exam_taking.submitting": "提出中...",
    "exam_taking.submit_anytime": "いつでも提出できます",
    "exam_taking.completed": "完了",

    // Results page
    "results.congratulations": "おめでとうございます！合格しました！",
    "results.not_passed": "不合格",
    "results.score": "スコア",
    "results.correct_answers": "正解",
    "results.answered": "回答済み",
    "results.accuracy": "正答率",
    "results.section_performance": "セクション別成績",
    "results.section_performance_desc": "スキル別の詳細スコア分析",
    "results.detailed_results": "詳細問題レビュー",
    "results.detailed_results_desc": "答えと詳細な説明を確認",
    "results.show_details": "詳細を表示",
    "results.hide_details": "詳細を非表示",
    "results.correct": "正解",
    "results.incorrect": "不正解",
    "results.no_answer": "無回答",
    "results.explanation": "解説：",
    "results.next_actions": "次のアクション",
    "results.retake": "この試験を再受験",
    "results.choose_other": "他の試験を選択",
    "results.home": "ホームに戻る",
    "results.summary": "結果サマリー",
    "results.total_questions": "総問題数：",
    "results.questions_answered": "回答済み問題：",
    "results.correct_count": "正解：",
    "results.incorrect_count": "不正解：",
    "results.passing_score": "合格点：",
    "results.advice": "アドバイス：",
    "results.advice_text": "弱い分野を復習してもう一度挑戦しましょう！",

    // Common
    "common.loading": "読み込み中...",
    "common.minutes": "分",
    "common.questions": "問",
    "common.participants": "人が受験",
    "common.question": "問題",
    "common.of": "の",
    "common.percent": "％",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("vi")

  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage && ["vi", "en", "ja"].includes(savedLanguage)) {
      setLanguage(savedLanguage)
    }
  }, [])

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem("language", lang)
  }

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)[typeof language]] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
